sudo: required
services:
  - docker

before_install:
  - docker build -t akyetisir/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akyetisir/react-test npm test

after_success:
  - docker build -t akyetisir/multi-client ./client
  - docker build -t akyetisir/multi-nginx ./nginx
  - docker build -t akyetisir/multi-server ./server
  - docker build -t akyetisir/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akyetisir/multi-client
  - docker push akyetisir/multi-nginx
  - docker push akyetisir/multi-server
  - docker push akyetisir/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-docker-env-2"
  bucket_name: "elasticbeanstalk-eu-north-1-908027404190"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"